//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFront.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.HelloWorldResponse HelloWorld(WebApplicationFront.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplicationFront.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerNewUser", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.registerNewUserResponse registerNewUser(WebApplicationFront.ServiceReference1.registerNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.registerNewUserResponse> registerNewUserAsync(WebApplicationFront.ServiceReference1.registerNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.loginResponse login(WebApplicationFront.ServiceReference1.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.loginResponse> loginAsync(WebApplicationFront.ServiceReference1.loginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.getUserResponse getUser(WebApplicationFront.ServiceReference1.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getUserResponse> getUserAsync(WebApplicationFront.ServiceReference1.getUserRequest request);
        
        // CODEGEN: Generating message contract since element name getSupplementListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSupplementList", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.getSupplementListResponse getSupplementList(WebApplicationFront.ServiceReference1.getSupplementListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSupplementList", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getSupplementListResponse> getSupplementListAsync(WebApplicationFront.ServiceReference1.getSupplementListRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createNewSupplement", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.createNewSupplementResponse createNewSupplement(WebApplicationFront.ServiceReference1.createNewSupplementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createNewSupplement", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.createNewSupplementResponse> createNewSupplementAsync(WebApplicationFront.ServiceReference1.createNewSupplementRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSupplement", ReplyAction="*")]
        WebApplicationFront.ServiceReference1.updateSupplementResponse updateSupplement(WebApplicationFront.ServiceReference1.updateSupplementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSupplement", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.updateSupplementResponse> updateSupplementAsync(WebApplicationFront.ServiceReference1.updateSupplementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteSupplement", ReplyAction="*")]
        void deleteSupplement(int supplementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteSupplement", ReplyAction="*")]
        System.Threading.Tasks.Task deleteSupplementAsync(int supplementId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplicationFront.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplicationFront.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerNewUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.registerNewUserRequestBody Body;
        
        public registerNewUserRequest() {
        }
        
        public registerNewUserRequest(WebApplicationFront.ServiceReference1.registerNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DOB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string role;
        
        public registerNewUserRequestBody() {
        }
        
        public registerNewUserRequestBody(string username, string email, string password, System.DateTime DOB, string gender, string role) {
            this.username = username;
            this.email = email;
            this.password = password;
            this.DOB = DOB;
            this.gender = gender;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.registerNewUserResponseBody Body;
        
        public registerNewUserResponse() {
        }
        
        public registerNewUserResponse(WebApplicationFront.ServiceReference1.registerNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registerNewUserResponseBody {
        
        public registerNewUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(WebApplicationFront.ServiceReference1.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(WebApplicationFront.ServiceReference1.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.getUserRequestBody Body;
        
        public getUserRequest() {
        }
        
        public getUserRequest(WebApplicationFront.ServiceReference1.getUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getUserRequestBody() {
        }
        
        public getUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.getUserResponseBody Body;
        
        public getUserResponse() {
        }
        
        public getUserResponse(WebApplicationFront.ServiceReference1.getUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserResult;
        
        public getUserResponseBody() {
        }
        
        public getUserResponseBody(string getUserResult) {
            this.getUserResult = getUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupplementListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSupplementList", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.getSupplementListRequestBody Body;
        
        public getSupplementListRequest() {
        }
        
        public getSupplementListRequest(WebApplicationFront.ServiceReference1.getSupplementListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSupplementListRequestBody {
        
        public getSupplementListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupplementListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSupplementListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.getSupplementListResponseBody Body;
        
        public getSupplementListResponse() {
        }
        
        public getSupplementListResponse(WebApplicationFront.ServiceReference1.getSupplementListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getSupplementListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSupplementListResult;
        
        public getSupplementListResponseBody() {
        }
        
        public getSupplementListResponseBody(string getSupplementListResult) {
            this.getSupplementListResult = getSupplementListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createNewSupplementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createNewSupplement", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.createNewSupplementRequestBody Body;
        
        public createNewSupplementRequest() {
        }
        
        public createNewSupplementRequest(WebApplicationFront.ServiceReference1.createNewSupplementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createNewSupplementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int TypeId;
        
        public createNewSupplementRequestBody() {
        }
        
        public createNewSupplementRequestBody(string name, System.DateTime date, int price, int TypeId) {
            this.name = name;
            this.date = date;
            this.price = price;
            this.TypeId = TypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createNewSupplementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createNewSupplementResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.createNewSupplementResponseBody Body;
        
        public createNewSupplementResponse() {
        }
        
        public createNewSupplementResponse(WebApplicationFront.ServiceReference1.createNewSupplementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class createNewSupplementResponseBody {
        
        public createNewSupplementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateSupplementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateSupplement", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.updateSupplementRequestBody Body;
        
        public updateSupplementRequest() {
        }
        
        public updateSupplementRequest(WebApplicationFront.ServiceReference1.updateSupplementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateSupplementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TypeId;
        
        public updateSupplementRequestBody() {
        }
        
        public updateSupplementRequestBody(int supplementId, string name, System.DateTime date, int price, int TypeId) {
            this.supplementId = supplementId;
            this.name = name;
            this.date = date;
            this.price = price;
            this.TypeId = TypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateSupplementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateSupplementResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationFront.ServiceReference1.updateSupplementResponseBody Body;
        
        public updateSupplementResponse() {
        }
        
        public updateSupplementResponse(WebApplicationFront.ServiceReference1.updateSupplementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateSupplementResponseBody {
        
        public updateSupplementResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebApplicationFront.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebApplicationFront.ServiceReference1.WebServiceSoap>, WebApplicationFront.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.HelloWorldResponse WebApplicationFront.ServiceReference1.WebServiceSoap.HelloWorld(WebApplicationFront.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplicationFront.ServiceReference1.HelloWorldRequest inValue = new WebApplicationFront.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.HelloWorldRequestBody();
            WebApplicationFront.ServiceReference1.HelloWorldResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.HelloWorldResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.HelloWorldAsync(WebApplicationFront.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplicationFront.ServiceReference1.HelloWorldRequest inValue = new WebApplicationFront.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.registerNewUserResponse WebApplicationFront.ServiceReference1.WebServiceSoap.registerNewUser(WebApplicationFront.ServiceReference1.registerNewUserRequest request) {
            return base.Channel.registerNewUser(request);
        }
        
        public void registerNewUser(string username, string email, string password, System.DateTime DOB, string gender, string role) {
            WebApplicationFront.ServiceReference1.registerNewUserRequest inValue = new WebApplicationFront.ServiceReference1.registerNewUserRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.registerNewUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.DOB = DOB;
            inValue.Body.gender = gender;
            inValue.Body.role = role;
            WebApplicationFront.ServiceReference1.registerNewUserResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).registerNewUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.registerNewUserResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.registerNewUserAsync(WebApplicationFront.ServiceReference1.registerNewUserRequest request) {
            return base.Channel.registerNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.registerNewUserResponse> registerNewUserAsync(string username, string email, string password, System.DateTime DOB, string gender, string role) {
            WebApplicationFront.ServiceReference1.registerNewUserRequest inValue = new WebApplicationFront.ServiceReference1.registerNewUserRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.registerNewUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.DOB = DOB;
            inValue.Body.gender = gender;
            inValue.Body.role = role;
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).registerNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.loginResponse WebApplicationFront.ServiceReference1.WebServiceSoap.login(WebApplicationFront.ServiceReference1.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string username, string password) {
            WebApplicationFront.ServiceReference1.loginRequest inValue = new WebApplicationFront.ServiceReference1.loginRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebApplicationFront.ServiceReference1.loginResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.loginResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.loginAsync(WebApplicationFront.ServiceReference1.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.loginResponse> loginAsync(string username, string password) {
            WebApplicationFront.ServiceReference1.loginRequest inValue = new WebApplicationFront.ServiceReference1.loginRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.getUserResponse WebApplicationFront.ServiceReference1.WebServiceSoap.getUser(WebApplicationFront.ServiceReference1.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public string getUser(string username) {
            WebApplicationFront.ServiceReference1.getUserRequest inValue = new WebApplicationFront.ServiceReference1.getUserRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.getUserRequestBody();
            inValue.Body.username = username;
            WebApplicationFront.ServiceReference1.getUserResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).getUser(inValue);
            return retVal.Body.getUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getUserResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.getUserAsync(WebApplicationFront.ServiceReference1.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getUserResponse> getUserAsync(string username) {
            WebApplicationFront.ServiceReference1.getUserRequest inValue = new WebApplicationFront.ServiceReference1.getUserRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.getUserRequestBody();
            inValue.Body.username = username;
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.getSupplementListResponse WebApplicationFront.ServiceReference1.WebServiceSoap.getSupplementList(WebApplicationFront.ServiceReference1.getSupplementListRequest request) {
            return base.Channel.getSupplementList(request);
        }
        
        public string getSupplementList() {
            WebApplicationFront.ServiceReference1.getSupplementListRequest inValue = new WebApplicationFront.ServiceReference1.getSupplementListRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.getSupplementListRequestBody();
            WebApplicationFront.ServiceReference1.getSupplementListResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).getSupplementList(inValue);
            return retVal.Body.getSupplementListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getSupplementListResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.getSupplementListAsync(WebApplicationFront.ServiceReference1.getSupplementListRequest request) {
            return base.Channel.getSupplementListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.getSupplementListResponse> getSupplementListAsync() {
            WebApplicationFront.ServiceReference1.getSupplementListRequest inValue = new WebApplicationFront.ServiceReference1.getSupplementListRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.getSupplementListRequestBody();
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).getSupplementListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.createNewSupplementResponse WebApplicationFront.ServiceReference1.WebServiceSoap.createNewSupplement(WebApplicationFront.ServiceReference1.createNewSupplementRequest request) {
            return base.Channel.createNewSupplement(request);
        }
        
        public void createNewSupplement(string name, System.DateTime date, int price, int TypeId) {
            WebApplicationFront.ServiceReference1.createNewSupplementRequest inValue = new WebApplicationFront.ServiceReference1.createNewSupplementRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.createNewSupplementRequestBody();
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.price = price;
            inValue.Body.TypeId = TypeId;
            WebApplicationFront.ServiceReference1.createNewSupplementResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).createNewSupplement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.createNewSupplementResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.createNewSupplementAsync(WebApplicationFront.ServiceReference1.createNewSupplementRequest request) {
            return base.Channel.createNewSupplementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.createNewSupplementResponse> createNewSupplementAsync(string name, System.DateTime date, int price, int TypeId) {
            WebApplicationFront.ServiceReference1.createNewSupplementRequest inValue = new WebApplicationFront.ServiceReference1.createNewSupplementRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.createNewSupplementRequestBody();
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.price = price;
            inValue.Body.TypeId = TypeId;
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).createNewSupplementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationFront.ServiceReference1.updateSupplementResponse WebApplicationFront.ServiceReference1.WebServiceSoap.updateSupplement(WebApplicationFront.ServiceReference1.updateSupplementRequest request) {
            return base.Channel.updateSupplement(request);
        }
        
        public void updateSupplement(int supplementId, string name, System.DateTime date, int price, int TypeId) {
            WebApplicationFront.ServiceReference1.updateSupplementRequest inValue = new WebApplicationFront.ServiceReference1.updateSupplementRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.updateSupplementRequestBody();
            inValue.Body.supplementId = supplementId;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.price = price;
            inValue.Body.TypeId = TypeId;
            WebApplicationFront.ServiceReference1.updateSupplementResponse retVal = ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).updateSupplement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.updateSupplementResponse> WebApplicationFront.ServiceReference1.WebServiceSoap.updateSupplementAsync(WebApplicationFront.ServiceReference1.updateSupplementRequest request) {
            return base.Channel.updateSupplementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFront.ServiceReference1.updateSupplementResponse> updateSupplementAsync(int supplementId, string name, System.DateTime date, int price, int TypeId) {
            WebApplicationFront.ServiceReference1.updateSupplementRequest inValue = new WebApplicationFront.ServiceReference1.updateSupplementRequest();
            inValue.Body = new WebApplicationFront.ServiceReference1.updateSupplementRequestBody();
            inValue.Body.supplementId = supplementId;
            inValue.Body.name = name;
            inValue.Body.date = date;
            inValue.Body.price = price;
            inValue.Body.TypeId = TypeId;
            return ((WebApplicationFront.ServiceReference1.WebServiceSoap)(this)).updateSupplementAsync(inValue);
        }
        
        public void deleteSupplement(int supplementId) {
            base.Channel.deleteSupplement(supplementId);
        }
        
        public System.Threading.Tasks.Task deleteSupplementAsync(int supplementId) {
            return base.Channel.deleteSupplementAsync(supplementId);
        }
    }
}
